services:
  bot:
    build: ./bot
    #command: python manage.py run -h 0.0.0.0 # python manage.py run -h 0.0.0.0
    volumes:
      - ./bot/:/bot/
    ports:
      - 5001:5000
    environment:
      FLASK_APP: __init__.py
